# Generator
num_filters: 64
num_filters_mlp: 256
style_dims: 64
num_res_blocks: 2
num_mlp_blocks: 3
num_downsamples_style: 5
num_downsamples_content: 4
num_image_channels: 3
weight_norm_type: 'none'
nonlinearity: 'relu'
coco_usb_dims: 1024
# VGG specifics
vgg_dim: 512
ConvBlocks: true

# discriminator: 
image_channels: 3
dis_num_filters: 64
dis_max_num_filters: 512
dis_num_layers: 4
dis_padding_mode: 'reflect'
dis_weight_norm_type: 'spectral'


